### PR TITLE
Custom session/device id generator support

### PR DESCRIPTION
**Pull request by Tvaroh**

### CODE REVIEW

**Comment by Tvaroh** [comment]
But functions don't accept implicit parameters, while we need `Async` instance in the default implementation.

**Comment by fomkin** [comment]
You already have `Async` instance through `KorolevServiceConfig` type parameters.

**Comment by Tvaroh** [comment]
You can't use it in the parameters.

**Comment by fomkin** [comment]
You mean we can't make default parameters?

**Comment by Tvaroh** [comment]
Yep.

**Comment by fomkin** [comment]
Ok, I accept. One more moment. What about users who already have unsecure ids?

**Comment by Tvaroh** [comment]
What can we do about that? Will their cookie expire eventually?

**Comment by fomkin** [comment]
I think not.

**Comment by fomkin** [comment]
Rebase please.

**Pull request merged**
