### PR TITLE
Cats effect integration module

### PR DESCRIPTION
**Pull request by road21**

### CODE REVIEW

**Comment by road21** [comment]
> Add license headers to new file using `sbt headerCreate`
I have also accidentally added license headers for 2 more files without them. Is it okey, or should I remove them?

**Comment by fomkin** [comment]
@road21 no thats fine, thanks.

**Comment by fomkin** [comment]
Build is failing on 2.11 https://travis-ci.org/fomkin/korolev/jobs/485978505#L549

**Comment by road21** [comment]
I have fixed 2.11 build. 2.12 build is still failing, but on master it is failing for the same reason. Should I fix this?

**Comment by fomkin** [comment]
@road21 no. integration-tests was suddenly broken one day.

**Comment by vovapolu** [comment]
@fomkin Can we merge this PR? I'd like to use `cats.effect` support in korolev. I'm currently using my own (not so good) version of the cats.effect integration. I can help to fix all the problems in the PR.

**Pull request merged**
